### ISSUE TITLE
404 : not found. when i click on the link it takes me to this

### ISSUE THREAD

**Issue by Laytonnnnnnn** [LuminesenceProject/LumiOS#10]
![Screenshot 2024-03-11 13 54 11](https://github.com/LuminesenceProject/LumiOS/assets/104936586/fdabe011-76d4-4d6a-9d4f-51733bcc20de)

**Comment by LuminesenceProject** [comment]
I updated the link so it should work now. 

Here is the link in case you need it:
https://raw.githubusercontent.com/LuminesenceProject/LumiOS/main/LumiOS.v5.html
