### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by hankypoo7** [LuminesenceProject/LumiOS#11]
when I go [here](https://raw.githubusercontent.com/LuminesenceProject/LumiOS/main/LumiOS.v6.html) it takes me to a 404 page.

**Comment by LuminesenceProject** [comment]
I fixed the link so it should work now!

Here is the link in case you need it: https://raw.githubusercontent.com/LuminesenceProject/LumiOS/main/LumiOS.v6.5.html.

**Comment by hankypoo7** [comment]
thank you I appreciate it
