### ISSUE TITLE
Broken will not load

### ISSUE THREAD

**Issue by Dogeamogus** [LuminesenceProject/LumiOS#12]
loads to the screen where it says the time and then leads to this sign up button does not do anthing
![Screenshot 2024-04-30 12 28 28 PM](https://github.com/LuminesenceProject/LumiOS/assets/115795516/97b9d462-c50d-437a-835e-87a3b31fbf33)
[

**Comment by LuminesenceProject** [comment]
1. In the bottom left, click sign-up, and create a new account
2. After the page has reloaded, click your new account in the bottom left
3. Sign in.
4. Enjoy!

**Comment by LuminesenceProject** [comment]
I'll mark this as finished as in the latest version, it no longer uses leaders.
