### ISSUE TITLE
Games not working

### ISSUE THREAD

**Issue by Bluubr** [LuminesenceProject/LumiOS#14]
When I play a game, this happens:
<img width="1469" alt="Screenshot 2024-05-02 at 3 19 34 PM" src="https://github.com/LuminesenceProject/LumiOS/assets/151577412/451e1005-0088-4e07-be88-4123f882463c">

**Comment by LuminesenceProject** [comment]
The page needs to be reloaded. Also make sure to wait a few seconds before closing the app store or installing another app, because it takes time to download.
