### ISSUE TITLE
Terraria Problems.

### ISSUE THREAD

**Issue by LopingUp** [LuminesenceProject/LumiOS#17]
During update 7.5 I was incapable of downloading games, in this new version I can and have been playing Terraria for hours, my problem is that the Terraria save code makes the website crash on whatever device I use, I don't know if this is a proxy issue or an issue that the original creator may have addressed, I was wondering if this was fixable? If it is please reach out!

**Comment by LuminesenceProject** [comment]
I've played Terraria a bunch, and I think its because the save file gets exponentially larger as the game progresses. I don't think its possible to do it without creating a simpler world that uses less data.
