### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by whynot4335** [LuminesenceProject/LumiOS#18]
This isn't an issue but I hope someone can help me. I really want to play some more Pico-8 games but I just don't know how to download the HTML because I like playing HTML. I'm hoping that someone will be able to give me the HTML for these games if not I hope the creator of Lumi will add these to games. The games are (https://www.lexaloffle.com/bbs/?tid=3200&pid=19680) and (https://www.lexaloffle.com/bbs/?pid=52226#p) I hope someone will give me these please and thank you.

**Comment by LuminesenceProject** [comment]
So they are open source and free to use, but they need a pico-8 subscription and unfortunately I don't plan on spending money on getting it. Maybe try to contact the developers and ask for an html version of those games.
