### ISSUE TITLE
Byp assing gogardian etc doesnt work

### ISSUE THREAD

**Issue by dude363635** [LuminesenceProject/LumiOS#2]
pls help me!
also cant resize windows to full screen pls add this feature!!!

**Comment by LuminesenceProject** [comment]
The browser app does not bypass GoGuardian or any other blocker. To access restricted content, you need a link to a specific website that has the ability to bypass such restrictions. 

I am currently addressing the issue with full-screen functionality, and this improvement will be included in the upcoming update. Meanwhile, to maximize a window, you'll need to manually click the maximize button when opening a new window.

don't worry though i'll add it

**Comment by dude363635** [comment]
Thankyou, does this include the option to resize windows by dragging them?
Also absolutely LOVE the work your doing! I really hat e gogardian!

**Comment by LuminesenceProject** [comment]
Thank you! 

I just Fixed the issue with the windows, so now you can fullscreen it, etc. 
Im going to mark this issue as completed for now.
