### ISSUE TITLE
crazy idea

### ISSUE THREAD

**Issue by Notahackeratall1001010** [LuminesenceProject/LumiOS#22]
by chance do you think you can add cloud gaming I would love to play some of my fav games on this but they cant be added
I don't know what this would take maybe a direct link to Xbox cloud gaming or ps play or something PC related but I think it would be really cool to play something like mortal Kombat or trailmakers or something in that term

sorry for this not being a real issue y'all are doing great :)

**Comment by LuminesenceProject** [comment]
Its not impossible to add, but what you are saying sounds like a proxy. I'll try to see if I can do that.

**Comment by Notahackeratall1001010** [comment]
Alright thanks also by chance can I ask when's next ubdate?

**Comment by LuminesenceProject** [comment]
This weekend probably.

**Comment by BlazingSplash82** [comment]
i dont know if this helps but geforce now might be possable thing you could add. its basically xbox cloud gaming on steroids. you can play on and link your steam xbox battle.net and ubisoft accounts and play all your games on any device. they also have a app that you can download from there website that works without having linux or the playstore enabled.

**Comment by BlazingSplash82** [comment]
it also can work like a proxy if you click sign in with google as it opens up a browser
