### ISSUE TITLE
How does the web browser work?

### ISSUE THREAD

**Issue by Charlieis1nsan3** [LuminesenceProject/LumiOS#25]
I  know that their is a web browser. but I found that it mostly opens  websites that use firebase how does it work? I am a interest developer?

**Comment by LuminesenceProject** [comment]
The web browser does not actually do anything. It is an iframe, it just displays the contents of a website without modifying it.  You can find the docs for iframes [here](https://www.w3schools.com/html/html_iframe.asp).

**Comment by Charlieis1nsan3** [comment]
I kinda forgot about this I already found out how it works, its just an embedded iframe.lol
