### ISSUE TITLE
Lumi OSv4

### ISSUE THREAD

**Issue by Borbius11** [LuminesenceProject/LumiOS#3]
When I open LumiOS.v4.html it opens but the tab is just blank and white
![Screenshot 2024-01-24 8 07 05 AM](https://github.com/LuminesenceProject/LumiOS/assets/156274260/177cb5e1-0f46-463e-bf5f-f6fb4da84e80)

**Comment by LuminesenceProject** [comment]
I've had that problem too, and the easiest way to solve it is by clearing browsing data and localstorage/cookies in the settings tab for your browser. If you can, please post the error messege from the console here so I can find and fix it in the future.

Thanks,

**Comment by Borbius11** [comment]
I still have the same issue but this time it flashes the loading screen and then goes white 
![image](https://github.com/LuminesenceProject/LumiOS/assets/156274260/2d3d10af-4bc9-4f31-9fd6-02c2303323f9)

**Comment by LuminesenceProject** [comment]
I think this has to do with the way the datas stored on chrome.

1. In the top left, click on the three dots and then click 'settings'
2. Click on Privacy and Security
3. Scroll down and click on Clear Browsing Data
4. Make sure it clears all of Lumi OS's data
<img width="1417" alt="Screenshot 2024-02-09 at 3 56 24 PM" src="https://github.com/LuminesenceProject/LumiOS/assets/101959214/9327c300-40a0-4b88-a0dd-8130b4bf10d0">

**Comment by LuminesenceProject** [comment]
I also added another feature, but you will have to update the current version, and download it again.

Simply type "lumiplus", in that exact order and it will wipe all data stored by it, which should fix the issue.
