### ISSUE TITLE
v4.5 File not found

### ISSUE THREAD

**Issue by PaytonsSins** [LuminesenceProject/LumiOS#4]
![Screenshot 2024-02-08 3 19 32 PM](https://github.com/LuminesenceProject/LumiOS/assets/125277897/15b6eb45-4d8c-443a-a4ca-ada9ca669efa)

**Comment by LuminesenceProject** [comment]
I just updated the link so it should work now

Heres the link it case you need it: 
https://raw.githubusercontent.com/LuminesenceProject/LumiOS/main/LumiOS.v4.2.html

**Comment by PaytonsSins** [comment]
Thanks, quick question though, how does the browser work, anytime I try to go somewhere is shows this: 
![Screenshot 2024-02-08 5 15 54 PM](https://github.com/LuminesenceProject/LumiOS/assets/125277897/0a7730ac-29a7-4b2f-85d1-50c3052bfcaf)

**Comment by LuminesenceProject** [comment]
That might be a blocker or something else, because some sights block connecting through an iframe.

**Comment by PaytonsSins** [comment]
Same thing as last time, could you fix it? About the issue last time, I do believe that is the case. My school district is pretty strict on chromebook capabilities, even Javascript is blocked.

**Comment by LuminesenceProject** [comment]
I don't think its possible to get around iframes unless you use an actual proxy. Here are some links that you can try. 
1: "https://findmytutor.info/"
2: "https://math.supplysolutionsmx.com/"
3: "https://government.sotna.org/"
4: "https://www.webapplication.design/"
5: "https://nooo-the.chubsinfestation.design/"
6: "https://algebra.stickyricecakes.com/"
7: "https://aux.hop.sh/"
8: "https://geometry.hacknperl.com/"
9: "https://e.pentafon.net/"
10: "https://learn2invest.info/"

**Comment by PaytonsSins** [comment]
Appreciate it.
