### ISSUE TITLE
White screen after restart

### ISSUE THREAD

**Issue by EcoliEater87** [LuminesenceProject/LumiOS#5]
I get a white screen of death after restarting. Have to clear cookies to fix. Don't know why it happens. Help would be appreciated.

**Comment by LuminesenceProject** [comment]
Sorry about that. It's because of the way the theme is applied when it first loads, (its undefined) so it just tries to apply it anyway, but causes a bunch of errors making the screen go white. 

It should be fixed in the new update. (v4.5).
