### ISSUE TITLE
White screen on startup

### ISSUE THREAD

**Issue by Borbius11** [LuminesenceProject/LumiOS#6]
sry to bother you but the same white screen is still happening

**Comment by Borbius11** [comment]
![Screenshot 2024-03-05 10 10 37 AM](https://github.com/LuminesenceProject/LumiOS/assets/156274260/16e96079-00cc-479f-a3ce-556d179f7f0f)

**Comment by LuminesenceProject** [comment]
Is there any other information you can provide? Keep in mind you can also type in: "lumiplus" all lowercase in order to be given a prompt to reset Lumi OS, which _should_ fix it.

**Comment by LuminesenceProject** [comment]
I just realized the issue. The file has to be unzipped, then you have to open the .html file.
