### ISSUE TITLE
Issue with JavaScript console

### ISSUE THREAD

**Issue by htmlmasterrace** [LuminesenceProject/LumiOS#8]
The JavaScript console is nice, but when I use alert('Hello World') it says 

"quickAccess>alert('hello world')
Lumi OS could not evaluate the code!
Are you sure it's proper javascript?
 
Lumi OS found this error:
Invalid or unexpected token"
but alert('test') works fine.

**Comment by LuminesenceProject** [comment]
In version 5 commands can now include spaces, so it should fix the issue. 

alert('hello world') should work now.
